# Alising the array

In [1]:
import numpy as np

In [2]:
a=np.array([32,43,23,42,24,433])

In [3]:
b=a

In [4]:
print(b)

[ 32  43  23  42  24 433]


### modifying 0th element of b

In [5]:
b[0]=34444

In [6]:
print(b)

[34444    43    23    42    24   433]


# viewing and copying array

In [7]:
a=np.arange(1,16)

In [8]:
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [10]:
b=a.view

In [11]:
print(b)

<built-in method view of numpy.ndarray object at 0x0000015D9B2A11D0>


In [15]:
b=a.view()

In [16]:
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [17]:
b[0]=9999

In [18]:
print(a)
print(b)

[9999    2    3    4    5    6    7    8    9   10   11   12   13   14
   15]
[9999    2    3    4    5    6    7    8    9   10   11   12   13   14
   15]


### Both changed original and viewded

In [19]:
c=a.copy()

In [20]:
print(c)

[9999    2    3    4    5    6    7    8    9   10   11   12   13   14
   15]


In [21]:
c[0]=1

In [22]:
print(a)
print(c)

[9999    2    3    4    5    6    7    8    9   10   11   12   13   14
   15]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


# Dimension of array

## ndim attribute

In [23]:
print(a.ndim)

1


In [24]:
arr=np.array([[1,2,4,2,3],[3,4,2,6,7]])
print(arr.ndim)

2


## shape attribute

In [25]:
print(arr.shape)

(2, 5)


#### change of array shape

In [26]:
arr.shape=(5,2)

In [27]:
print(arr)

[[1 2]
 [4 2]
 [3 3]
 [4 2]
 [6 7]]


## size attribute

In [28]:
print(arr.size)

10


## itemsize attribute

#### it gives the memory size of the array

In [29]:
print(arr.itemsize)

8


## dtype attribute

In [30]:
print(arr)
print(arr.dtype)


[[1 2]
 [4 2]
 [3 3]
 [4 2]
 [6 7]]
int64


In [31]:
arr2=np.array([3.4,23.4,32.4,244.53,32.53,24.2])

In [32]:
print(arr2)

[  3.4   23.4   32.4  244.53  32.53  24.2 ]


## nbytes attribute

#### total number of bytes = size of the array * item size of each element

In [34]:
print(arr.nbytes)

80


## reshape() method

In [37]:
arr1=np.arange(1,11)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [39]:
arr1=arr1.reshape(2,5)

In [40]:
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [41]:
arr1=arr1.reshape(5,2)

In [42]:
print(arr1)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


## flatten() method

In [43]:
print(arr1.flatten())

[ 1  2  3  4  5  6  7  8  9 10]
