# create a numpy array

In [1]:
import numpy as np

In [2]:
a=np.array([2,3,5,6,3,6])

In [3]:
print(a)

[2 3 5 6 3 6]


In [4]:
a

array([2, 3, 5, 6, 3, 6])

## create array using linespace

In [6]:
b=np.linspace(0,10,7)

In [7]:
b

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [8]:
c=np.linspace(0,10,5)

In [9]:
c

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### linespace(start,stop,n)

In [10]:
d=np.linspace(0,20,10)

In [11]:
d

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

## create array using logspace()

In [12]:
ab=np.logspace(1,4,5)

In [13]:
ab

array([   10.        ,    56.23413252,   316.22776602,  1778.27941004,
       10000.        ])

### here 1 is the power of 10 from which program start and 4 is the power of 10 to which program end

In [15]:
ab1=np.logspace(5,7,8)

In [16]:
ab1

array([  100000.        ,   193069.77288832,   372759.37203149,
         719685.67300115,  1389495.49437314,  2682695.79527973,
        5179474.67923121, 10000000.        ])

## creating array using arrange()

### arange(start,stop,stepsize)

In [17]:
ab2=np.arange(0,20,2)

In [18]:
ab2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## creating array using zeros and ones()

### zeros(n,datatype) ones(n,datatype)

In [19]:
zeros1=np.zeros(6,int)

In [20]:
zeros1

array([0, 0, 0, 0, 0, 0])

In [21]:
ones1=np.ones(6,float)

In [22]:
ones1

array([1., 1., 1., 1., 1., 1.])

In [24]:
ones2=np.ones(6,str)

In [25]:
print(ones2)

['1' '1' '1' '1' '1' '1']


## Mathematical operation on array

In [27]:
arr=np.array([1,2,3,4,5])

In [29]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427])

In [30]:
np.cos(arr)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219])

In [31]:
np.tan(arr)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128, -3.38051501])

In [32]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [33]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [34]:
np.power(arr,n)

NameError: name 'n' is not defined

In [35]:
np.power(arr,5)

array([   1,   32,  243, 1024, 3125])

In [36]:
np.exp(arr)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [37]:
np.sum(arr)

np.int64(15)

In [38]:
np.prod(arr)

np.int64(120)

In [39]:
arr1=np.array([32,531,25,53,523,14])

In [40]:
np.min(arr1)

np.int64(14)

In [41]:
np.max(arr1)

np.int64(531)

In [42]:
np.mean(arr1)

np.float64(196.33333333333334)

In [43]:
np.median(arr1)

np.float64(42.5)

In [44]:
np.var(arr1)

np.float64(54810.55555555554)

In [45]:
np.var(arr)

np.float64(2.0)

In [48]:
np.concatenate([arr,arr1])

array([  1,   2,   3,   4,   5,  32, 531,  25,  53, 523,  14])

In [50]:
np.sort(arr1)

array([ 14,  25,  32,  53, 523, 531])

## comparing array

In [51]:
a= np.array([5,2,6,3,0])
b=np.array([2,6,5,3,0])

In [52]:
c= a==b
print("Result of a==b : ",c)

Result of a==b :  [False False False  True  True]


In [53]:
c= a>b

In [54]:
print(c)

[ True False  True False False]


In [55]:
c=a<=b

In [56]:
print(c)

[False  True False  True  True]


### using any() and all()

In [59]:
print("Check any element is true : ",np.any(c))

Check any element is true :  True


In [60]:
print("Check all elements are true : ",np.all(c))

Check all elements are true :  False


### logical FUNCTION

In [61]:
a=np.array([0,1,2,3,4])

In [62]:
b=np.array([0,1,2,3,4])

In [63]:
c= logical_and(a>0,a<5)

NameError: name 'logical_and' is not defined

In [1]:
c= np.logical_and(a>0,a<4)

NameError: name 'np' is not defined

In [65]:
c

array([False,  True,  True,  True, False])

In [66]:
print(np.logical_or(b>=3,b==1))

[False  True False  True  True]


In [67]:
print(np.logical_not(a))

[ True False False False False]


### using where()

#### where(condition,expression1,expression2)

In [68]:
ab=np.array([42,63,24,6,124,63,24,65,2],int)

In [69]:
ba=np.array([32,42,5,24,52,233,53,24,65],int)

In [79]:
c=np.where(ab > ba, ab, ba)

NameError: name 'ba' is not defined

In [81]:
a=np.array([2,3,4])
b=np.array([4,3,2])
c=np.where(a>b,a,b)

In [82]:
c

array([4, 3, 4])